### ISSUE TITLE
Tooltip with `arrow` & more customizable options

### ISSUE THREAD

**Issue by swapnils19** [krzysu/flot.tooltip#149]
I am trying generate a tooltip as shown in [this](http://www.w3schools.com/css/tryit.asp?filename=trycss_tooltip_arrow_bottom) example.

But it seems like we can't specify any further customizations besides basic font/color options (atleast I didn't come across any example).

I also tried to turn off the `defaultTheme` option. Is there any way we can generate a tooltip like the given link?

**Comment by krzysu** [comment]
the way to go is to set 'defaultTheme' to false and write your own CSS, something like:

    .flotTip {
        background-color: black;
        color: #fff;
        text-align: center;
        border-radius: 6px;
        padding: 5px 0;
        z-index: 1040;
    }

    .flotTip::after {
        content: "";
        position: absolute;
        top: 100%;
        left: 50%;
        margin-left: -5px;
        border-width: 5px;
        border-style: solid;
        border-color: black transparent transparent transparent;
    }

but I didn't test it

**Comment by swapnils19** [comment]
thanks for the reply @krzysu 
tried your code.
the theme is as expected.
though I did a few changes to match better - 
```css
.flotTip {
    background-color: black;
    color: #fff;
    text-align: center;
    border-radius: 6px;
    padding: 5px 0;
    z-index: 1040;
    width: 120px;
    font-size: 14px;
}

.flotTip::after {
    content: " ";
    position: absolute;
    top: 50%;
    right: 100%;
    margin-top: -5px;
    border-width: 5px;
    border-style: solid;
    border-color: transparent black transparent transparent;
}
```

But the issue of the tooltip position is still there.

I was referencing [this](http://stackoverflow.com/questions/27416820/how-to-customize-flot-tooltip-in-angularjs) question, but I didn't get much success to write down my own code(Newbie to JS).

For now I am moving forward with the position as it is default. But I hope devs will make some options available for more customization of the tooltip. :)
